### ISSUE TITLE
能否将数据上传到其他空间？

### ISSUE THREAD

**Issue by stereomatchingkiss** [brightmart/nlp_chinese_corpus#19]
目前的空间，非中国的用户很难下载，请问是否可以上传资料到其他空间上？谢谢

**Comment by winse** [comment]
用迅雷下载，或者：

链接：https://pan.baidu.com/s/1of4csxBpU6MX7oW0tEprIg 
提取码：5nsn 
复制这段内容后打开百度网盘手机App，操作更方便哦
