### ISSUE TITLE
请问维基百科文件中文件夹的AA，AB...AM代表什么？

### ISSUE THREAD

**Issue by mikiihuang** [brightmart/nlp_chinese_corpus#2]
非常感谢您的分享，请问这些是什么分类？
![image](https://user-images.githubusercontent.com/29434338/52684817-811e2080-2f82-11e9-90af-345c94eb47de.png)

**Comment by brightmart** [comment]
你好，这些是将类似的词条放在一起，但并不是严格意义的分类。

**Comment by mikiihuang** [comment]
> 你好，这些是将类似的词条放在一起，但并不是严格意义的分类。

谢谢～
