### ISSUE TITLE
推荐一个训练好的embeddings / Recommendation of pre-trained embeddings

### ISSUE THREAD

**Issue by ZihengZZH** [brightmart/nlp_chinese_corpus#25]
推荐一个腾讯AI实验室最近release的中文embeddings，不太清楚他们的corpus是
I would like to recommend recently released pre-trained, Chinese-based, word embeddings. I don't quite know the corpus they trained the embeddings on, though.

https://ai.tencent.com/ailab/nlp/embedding.html

Hope it helps.

**Comment by brightmart** [comment]
great job.
