### ISSUE TITLE
请提供百度网盘外其他下载方式

### ISSUE THREAD

**Issue by CathyLin1219** [brightmart/nlp_chinese_corpus#26]
请提供百度网盘外其他下载方式吧，谷歌的云端硬盘个人的也有15G，腾讯微盘也行，百度真的下不下来啊，不能大家都去开会员吧，很痛苦啊……或者像另一位说的用torrent也可以吧。诚恳的请求大佬考虑一下该建议，感谢！

**Comment by brightmart** [comment]
好的，你的建议很好。这周更新一下地址。

**Comment by brightmart** [comment]
已经更新，添加了google drive下载方式，谢谢
