### ISSUE TITLE
google drive 下载好慢。能否提供云盘版本的？感谢

### ISSUE THREAD

**Issue by ArrogantL** [brightmart/nlp_chinese_corpus#33]

**Comment by frkhit** [comment]
我在[新的提交](https://github.com/brightmart/nlp_chinese_corpus/pull/34) 中提供了部分数据集的百度网盘链接

**Comment by ArrogantL** [comment]
非常感谢！

**Comment by v-yunbin** [comment]
@ArrogantL 能否为”社区问答json版“数据提供百度云下载？下载失败
